import type {
  Difficulty,
  GameMode,
  Question,
  QuestionCategory,
  SortOrder,
  SpicyLevel,
} from "@/types/game";

export const PLAYER_COUNT_OPTIONS = [3, 4, 5, 6, 7, 8] as const;
export const ROUND_OPTIONS = [3, 5, 7, 10] as const;

export const CATEGORY_META: Record<
  QuestionCategory,
  { label: string; description: string; icon: string }
> = {
  acquaintance: {
    label: "初対面向け",
    description: "距離感がまだ近すぎない場でも答えやすい",
    icon: "hand",
  },
  friends: {
    label: "友達向け",
    description: "いつもの関係性だからズレが見えやすい",
    icon: "users",
  },
  romance: {
    label: "恋愛寄り",
    description: "恋の温度感や攻め方のズレを楽しむ",
    icon: "heart",
  },
  party: {
    label: "飲み会向け",
    description: "テンション高めで盛り上がりやすい",
    icon: "sparkles",
  },
  light: {
    label: "ライト",
    description: "気軽に回せる日常系の軽いお題",
    icon: "sun",
  },
};

export const MODE_META: Record<
  GameMode,
  { label: string; description: string }
> = {
  normal: {
    label: "ノーマル",
    description: "結果を見て会話を楽しむ基本モード",
  },
  scored: {
    label: "点数あり",
    description: "予想順位の的中数を積み上げる",
  },
  compatibility: {
    label: "相性診断",
    description: "回答差が近いペアを最後に表示する",
  },
};

type ProfileName =
  | "minutes120"
  | "minutes180"
  | "percent"
  | "scale5"
  | "scale10"
  | "stepperCount"
  | "stepperMoney"
  | "custom4"
  | "custom6";

type QuestionSeed = {
  text: string;
  profile: ProfileName;
  minLabel: string;
  maxLabel: string;
  difficulty: Difficulty;
  spicyLevel: SpicyLevel;
  tags: string[];
  sortOrder?: SortOrder;
  rankingHint?: string;
  scaleLabels?: string[];
};

const profiles: Record<
  ProfileName,
  Omit<
    Question,
    | "id"
    | "category"
    | "text"
    | "minLabel"
    | "maxLabel"
    | "difficulty"
    | "spicyLevel"
    | "tags"
    | "rankingHint"
    | "sortOrder"
  >
> = {
  minutes120: {
    answerType: "number_slider",
    min: 0,
    max: 120,
    step: 5,
    defaultValue: 30,
    unit: "分",
    instructionText: "数字（分）で答えてね",
    timerSeconds: 30,
  },
  minutes180: {
    answerType: "number_slider",
    min: 0,
    max: 180,
    step: 10,
    defaultValue: 60,
    unit: "分",
    instructionText: "数字（分）で答えてね",
    timerSeconds: 30,
  },
  percent: {
    answerType: "percentage_slider",
    min: 0,
    max: 100,
    step: 10,
    defaultValue: 50,
    unit: "%",
    instructionText: "%で答えてね",
    timerSeconds: 25,
  },
  scale5: {
    answerType: "scale_1_5",
    min: 1,
    max: 5,
    step: 1,
    defaultValue: 3,
    unit: "点",
    instructionText: "1〜5点で答えてね",
    timerSeconds: 20,
  },
  scale10: {
    answerType: "scale_1_10",
    min: 1,
    max: 10,
    step: 1,
    defaultValue: 5,
    unit: "点",
    instructionText: "1〜10点で答えてね",
    timerSeconds: 20,
  },
  stepperCount: {
    answerType: "stepper",
    min: 0,
    max: 12,
    step: 1,
    defaultValue: 3,
    unit: "回",
    instructionText: "回数で答えてね",
    timerSeconds: 20,
  },
  stepperMoney: {
    answerType: "stepper",
    min: 0,
    max: 20000,
    step: 500,
    defaultValue: 5000,
    unit: "円",
    instructionText: "金額で答えてね",
    timerSeconds: 20,
  },
  custom4: {
    answerType: "custom_scale",
    min: 1,
    max: 4,
    step: 1,
    defaultValue: 2,
    unit: "",
    instructionText: "4段階で答えてね",
    timerSeconds: 20,
  },
  custom6: {
    answerType: "custom_scale",
    min: 1,
    max: 6,
    step: 1,
    defaultValue: 3,
    unit: "",
    instructionText: "6段階で答えてね",
    timerSeconds: 20,
  },
};

function createRankingHint(
  minLabel: string,
  maxLabel: string,
  sortOrder: SortOrder,
): string {
  return sortOrder === "asc"
    ? `「${minLabel}」側から順に並べよう`
    : `「${maxLabel}」側から順に並べよう`;
}

function buildQuestions(
  category: QuestionCategory,
  seeds: QuestionSeed[],
  startAt = 0,
): Question[] {
  return seeds.map((seed, index) => {
    const profile = profiles[seed.profile];
    const sortOrder = seed.sortOrder ?? "asc";

    return {
      id: `${category}-${String(startAt + index + 1).padStart(2, "0")}`,
      category,
      text: seed.text,
      ...profile,
      minLabel: seed.minLabel,
      maxLabel: seed.maxLabel,
      rankingHint:
        seed.rankingHint ?? createRankingHint(seed.minLabel, seed.maxLabel, sortOrder),
      sortOrder,
      difficulty: seed.difficulty,
      spicyLevel: seed.spicyLevel,
      tags: seed.tags,
      scaleLabels: seed.scaleLabels,
    };
  });
}

const acquaintanceSeeds: QuestionSeed[] = [
  {
    text: "初対面の人と打ち解ける速さは？",
    profile: "scale10",
    minLabel: "ゆっくり",
    maxLabel: "一瞬",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "会話", "社交性"],
  },
  {
    text: "沈黙が気まずくなるまで何秒くらい耐えられる？",
    profile: "minutes120",
    minLabel: "すぐ気まずい",
    maxLabel: "かなり平気",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "空気感", "沈黙"],
  },
  {
    text: "自己紹介でちょっと笑いを取りにいく度合いは？",
    profile: "scale5",
    minLabel: "無難派",
    maxLabel: "攻める",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "自己紹介", "ノリ"],
  },
  {
    text: "初対面の飲み会で連絡先を交換するハードルは？",
    profile: "scale10",
    minLabel: "かなり低い",
    maxLabel: "かなり高い",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "距離感", "連絡先"],
  },
  {
    text: "名前を一発で覚えていられる自信は？",
    profile: "percent",
    minLabel: "忘れがち",
    maxLabel: "かなり覚える",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "記憶", "印象"],
  },
  {
    text: "知らないグループに自然に混ざれる度胸は？",
    profile: "percent",
    minLabel: "混ざれない",
    maxLabel: "余裕",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "合流", "度胸"],
  },
  {
    text: "初対面で自分の趣味の話を出すまでの速さは？",
    profile: "scale10",
    minLabel: "かなり様子見",
    maxLabel: "すぐ出す",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "趣味", "話題"],
  },
  {
    text: "相手の共通点を見つけるのが得意なほう？",
    profile: "scale10",
    minLabel: "苦手",
    maxLabel: "得意",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "共通点", "会話"],
  },
  {
    text: "初対面の相手にまた会いたいと思わせる自信は？",
    profile: "scale5",
    minLabel: "自信なし",
    maxLabel: "かなりある",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "第一印象", "自信"],
  },
  {
    text: "人見知りが表に出やすい度合いは？",
    profile: "scale10",
    minLabel: "出にくい",
    maxLabel: "すぐ出る",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "人見知り", "性格"],
  },
  {
    text: "初対面で質問役に回る割合は？",
    profile: "percent",
    minLabel: "自分が話す",
    maxLabel: "質問多め",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "会話", "聞き上手"],
  },
  {
    text: "場の空気に合わせてテンションを調整する柔軟さは？",
    profile: "scale5",
    minLabel: "ぶれない",
    maxLabel: "かなり合わせる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "空気", "柔軟性"],
  },
  {
    text: "初対面で褒め言葉を自然に言える度合いは？",
    profile: "scale10",
    minLabel: "照れる",
    maxLabel: "自然に言える",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "褒め", "コミュ力"],
  },
  {
    text: "初対面の飲み会で帰るまでに何人とちゃんと話したい？",
    profile: "stepperCount",
    minLabel: "少人数で十分",
    maxLabel: "できるだけ全員",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "飲み会", "交流"],
  },
  {
    text: "会話の入り口として天気や食べ物の話を使う頻度は？",
    profile: "scale5",
    minLabel: "ほぼ使わない",
    maxLabel: "かなり使う",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "雑談", "話題選び"],
  },
  {
    text: "初対面の場で緊張しても顔に出ない度合いは？",
    profile: "percent",
    minLabel: "すぐ出る",
    maxLabel: "かなり隠せる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "緊張", "表情"],
  },
  {
    text: "輪の中心より、まずは横の人から仲良くなるタイプ？",
    profile: "custom4",
    minLabel: "中心へ行く",
    maxLabel: "横から入る",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "立ち回り", "距離感"],
    scaleLabels: ["中心直行", "やや中心", "やや横から", "横からゆっくり"],
  },
  {
    text: "初対面の相手に自分の失敗談を出せる度合いは？",
    profile: "scale5",
    minLabel: "出せない",
    maxLabel: "けっこう出せる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "自己開示", "会話"],
  },
  {
    text: "はじめましての挨拶から、相手を『話しやすい』と思うまでの速さは？",
    profile: "scale10",
    minLabel: "じっくり",
    maxLabel: "かなり早い",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "第一印象", "直感"],
  },
  {
    text: "初対面で印象に残る服装や小物を選ぶ度合いは？",
    profile: "scale5",
    minLabel: "控えめ",
    maxLabel: "印象重視",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "見た目", "印象"],
  },
];

const friendsSeeds: QuestionSeed[] = [
  {
    text: "友達の相談なら何分くらいでも聞ける？",
    profile: "minutes180",
    minLabel: "手短に",
    maxLabel: "いくらでも",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "相談", "聞き役"],
  },
  {
    text: "待ち合わせで遅れてきても許せるのは何分まで？",
    profile: "minutes120",
    minLabel: "数分でも気になる",
    maxLabel: "かなり待てる",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "遅刻", "寛容"],
  },
  {
    text: "既読スルーされても気にしないでいられるのは何日くらい？",
    profile: "stepperCount",
    minLabel: "その日で気になる",
    maxLabel: "かなり待てる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "LINE", "距離感"],
  },
  {
    text: "友達の無茶ぶりに付き合える度合いは？",
    profile: "scale10",
    minLabel: "かなり断る",
    maxLabel: "だいたい乗る",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "ノリ", "無茶ぶり"],
  },
  {
    text: "グループ旅行の計画はどれくらい細かく立てたい？",
    profile: "scale5",
    minLabel: "ざっくり",
    maxLabel: "かなり細かく",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "旅行", "計画性"],
  },
  {
    text: "友達の誕生日に使う予算感は？",
    profile: "stepperMoney",
    minLabel: "気持ち重視",
    maxLabel: "ちゃんとかける",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "プレゼント", "金額"],
  },
  {
    text: "深夜の呼び出しに応じる確率は？",
    profile: "percent",
    minLabel: "ほぼ行かない",
    maxLabel: "かなり行く",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "深夜", "フッ軽"],
  },
  {
    text: "友達のちょっとした変化に気づく自信は？",
    profile: "scale10",
    minLabel: "鈍感",
    maxLabel: "かなり気づく",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "観察", "気配り"],
  },
  {
    text: "一緒にいて沈黙でも平気な度合いは？",
    profile: "scale5",
    minLabel: "少し気まずい",
    maxLabel: "むしろ楽",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "空気感", "沈黙"],
  },
  {
    text: "ケンカしたとき、自分から先に謝るまでの速さは？",
    profile: "scale10",
    minLabel: "かなり遅い",
    maxLabel: "かなり早い",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "ケンカ", "仲直り"],
  },
  {
    text: "友達の新しい趣味に付き合える回数は月に何回くらい？",
    profile: "stepperCount",
    minLabel: "たまに",
    maxLabel: "かなり付き合う",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "趣味", "付き合い"],
  },
  {
    text: "ノープランでも遊びに出られる気軽さは？",
    profile: "scale10",
    minLabel: "準備したい",
    maxLabel: "即出られる",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "ノープラン", "フットワーク"],
  },
  {
    text: "友達の遅刻にちゃんとツッコむ強さは？",
    profile: "scale5",
    minLabel: "流す",
    maxLabel: "しっかり言う",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "ツッコミ", "遅刻"],
  },
  {
    text: "遊びの思い出写真を撮る枚数はどれくらい？",
    profile: "stepperCount",
    minLabel: "ほぼ撮らない",
    maxLabel: "かなり撮る",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "写真", "思い出"],
  },
  {
    text: "友達の秘密を守り切れる自信は？",
    profile: "percent",
    minLabel: "うっかり漏らしそう",
    maxLabel: "かなり守る",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "秘密", "信頼"],
  },
  {
    text: "友達の恋バナなら何分でも聞ける？",
    profile: "minutes180",
    minLabel: "ほどほど",
    maxLabel: "ずっと聞ける",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "恋バナ", "会話"],
  },
  {
    text: "グループで遊ぶとき、まとめ役に回りがちな度合いは？",
    profile: "scale10",
    minLabel: "任せたい",
    maxLabel: "自分がやる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "まとめ役", "リーダー"],
  },
  {
    text: "友達のサプライズを仕掛けるのはどれくらい好き？",
    profile: "scale5",
    minLabel: "苦手",
    maxLabel: "かなり好き",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "サプライズ", "イベント"],
  },
  {
    text: "『これ似合うと思った』で友達に物を買う頻度は？",
    profile: "custom4",
    minLabel: "ほぼない",
    maxLabel: "けっこうある",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "プレゼント", "衝動"],
    scaleLabels: ["ない", "たまに", "わりとある", "かなりある"],
  },
  {
    text: "大人数より少人数の集まりを好む度合いは？",
    profile: "scale10",
    minLabel: "大人数派",
    maxLabel: "少人数派",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "集まり", "好み"],
  },
];

const romanceSeeds: QuestionSeed[] = [
  {
    text: "気になる人に自分からいける度胸は？",
    profile: "percent",
    minLabel: "いけない",
    maxLabel: "かなりいける",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "アプローチ", "度胸"],
  },
  {
    text: "好きバレしても平気でいられる度合いは？",
    profile: "scale10",
    minLabel: "かなり無理",
    maxLabel: "むしろ平気",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "好意", "メンタル"],
  },
  {
    text: "返信待ちでソワソワする度合いは？",
    profile: "scale5",
    minLabel: "ほぼしない",
    maxLabel: "かなりする",
    difficulty: 1,
    spicyLevel: 2,
    tags: ["恋愛", "返信", "気持ち"],
  },
  {
    text: "恋人に会わないと寂しくなるまで何日くらい？",
    profile: "stepperCount",
    minLabel: "すぐ寂しい",
    maxLabel: "けっこう平気",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "会う頻度", "距離感"],
  },
  {
    text: "初デートのプランを自分で決めたい度合いは？",
    profile: "scale10",
    minLabel: "任せたい",
    maxLabel: "自分で決めたい",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["恋愛", "デート", "主導権"],
  },
  {
    text: "嫉妬しても顔に出さずにいられる度合いは？",
    profile: "percent",
    minLabel: "すぐ出る",
    maxLabel: "かなり隠せる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "嫉妬", "表情"],
  },
  {
    text: "手をつなぐまでの慎重さは？",
    profile: "scale10",
    minLabel: "かなり勢い派",
    maxLabel: "かなり慎重",
    difficulty: 1,
    spicyLevel: 2,
    tags: ["恋愛", "スキンシップ", "慎重"],
  },
  {
    text: "好きな人の前で自然体でいられる度合いは？",
    profile: "scale5",
    minLabel: "かなり崩れる",
    maxLabel: "ほぼ自然体",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 2,
    tags: ["恋愛", "緊張", "自然体"],
  },
  {
    text: "告白するなら何回目のデートまで待てる？",
    profile: "stepperCount",
    minLabel: "かなり早い",
    maxLabel: "じっくり",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "告白", "ペース"],
  },
  {
    text: "恋愛相談を友達にする割合は？",
    profile: "percent",
    minLabel: "自分で抱える",
    maxLabel: "かなり相談する",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["恋愛", "相談", "共有"],
  },
  {
    text: "相手の趣味に合わせる柔軟さは？",
    profile: "scale10",
    minLabel: "自分優先",
    maxLabel: "かなり合わせる",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["恋愛", "歩み寄り", "柔軟性"],
  },
  {
    text: "サプライズ演出への憧れはどれくらい？",
    profile: "scale5",
    minLabel: "いらない",
    maxLabel: "かなり好き",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["恋愛", "サプライズ", "演出"],
  },
  {
    text: "恋人と連絡を取りたい頻度は1日に何回くらい？",
    profile: "stepperCount",
    minLabel: "必要なときだけ",
    maxLabel: "かなりこまめ",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 2,
    tags: ["恋愛", "連絡頻度", "距離感"],
  },
  {
    text: "記念日を重視する度合いは？",
    profile: "scale10",
    minLabel: "そこまで",
    maxLabel: "かなり重視",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["恋愛", "記念日", "イベント"],
  },
  {
    text: "相手に甘えるのが得意なほう？",
    profile: "scale5",
    minLabel: "かなり苦手",
    maxLabel: "かなり得意",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "甘え", "距離感"],
  },
  {
    text: "一目惚れしやすい度合いは？",
    profile: "scale10",
    minLabel: "ほぼしない",
    maxLabel: "かなりする",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["恋愛", "一目惚れ", "直感"],
  },
  {
    text: "理想と現実のギャップを恋愛で許せる度合いは？",
    profile: "scale10",
    minLabel: "かなり厳しい",
    maxLabel: "かなり許せる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "理想", "現実"],
  },
  {
    text: "別れ話を切り出すのが苦手な度合いは？",
    profile: "scale5",
    minLabel: "わりとできる",
    maxLabel: "かなり苦手",
    difficulty: 3,
    spicyLevel: 3,
    tags: ["恋愛", "別れ", "重さ"],
  },
  {
    text: "好きな人がいると相手のSNSを見てしまう頻度は？",
    profile: "custom6",
    minLabel: "ほぼ見ない",
    maxLabel: "かなり見る",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "SNS", "気になる"],
    scaleLabels: ["見ない", "たまに", "少し見る", "わりと見る", "かなり見る", "更新待ち"],
  },
  {
    text: "デートで奢る・奢られるをどれくらい気にする？",
    profile: "scale10",
    minLabel: "ほぼ気にしない",
    maxLabel: "かなり気にする",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "お金", "価値観"],
  },
];

const partySeeds: QuestionSeed[] = [
  {
    text: "飲み会で最初の一杯を決める速さは？",
    profile: "scale10",
    minLabel: "かなり迷う",
    maxLabel: "即決",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "注文", "テンポ"],
  },
  {
    text: "カラオケでトップバッターに行ける度合いは？",
    profile: "scale10",
    minLabel: "かなり無理",
    maxLabel: "余裕",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "カラオケ", "度胸"],
  },
  {
    text: "二次会まで残る確率は？",
    profile: "percent",
    minLabel: "一次会で帰る",
    maxLabel: "だいたい残る",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "二次会", "体力"],
  },
  {
    text: "場を盛り上げ役に回る度合いは？",
    profile: "scale5",
    minLabel: "見守る派",
    maxLabel: "前に出る",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "盛り上げ", "役割"],
  },
  {
    text: "乾杯のテンションはどれくらい高い？",
    profile: "scale10",
    minLabel: "落ち着き派",
    maxLabel: "かなり高い",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "乾杯", "テンション"],
  },
  {
    text: "おつまみをシェアしようとする積極性は？",
    profile: "scale5",
    minLabel: "各自でいい",
    maxLabel: "かなり勧める",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "シェア", "気配り"],
  },
  {
    text: "その場で新しいゲームを始めようとする度合いは？",
    profile: "scale10",
    minLabel: "様子見",
    maxLabel: "すぐ提案",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "ゲーム", "提案"],
  },
  {
    text: "飲み会で写真を撮る枚数はどれくらい？",
    profile: "stepperCount",
    minLabel: "ほぼ撮らない",
    maxLabel: "かなり撮る",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "写真", "記録"],
  },
  {
    text: "初対面混じりの飲み会でも満足して帰れる度合いは？",
    profile: "scale10",
    minLabel: "疲れやすい",
    maxLabel: "かなり楽しめる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["飲み会", "初対面", "適応"],
  },
  {
    text: "終電を気にし始めるのは何分前くらい？",
    profile: "minutes120",
    minLabel: "ギリギリ派",
    maxLabel: "かなり早め",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "終電", "帰宅"],
  },
  {
    text: "酔うと声が大きくなりやすい度合いは？",
    profile: "scale5",
    minLabel: "変わらない",
    maxLabel: "かなり大きくなる",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "お酒", "変化"],
  },
  {
    text: "お酒なしでも場を楽しめる自信は？",
    profile: "percent",
    minLabel: "お酒がほしい",
    maxLabel: "かなり楽しめる",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "お酒", "空気"],
  },
  {
    text: "店選びを任されたい度合いは？",
    profile: "scale10",
    minLabel: "任されたくない",
    maxLabel: "任されたい",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "店選び", "主導"],
  },
  {
    text: "ハプニングを笑いに変えられる度合いは？",
    profile: "scale5",
    minLabel: "焦る",
    maxLabel: "かなり笑える",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["飲み会", "ハプニング", "切り返し"],
  },
  {
    text: "飲み会後に『今日はありがとう』を送る確率は？",
    profile: "percent",
    minLabel: "ほぼ送らない",
    maxLabel: "だいたい送る",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "フォロー", "連絡"],
  },
  {
    text: "一発芸の無茶ぶりに耐えられる度合いは？",
    profile: "scale10",
    minLabel: "かなり無理",
    maxLabel: "乗り切れる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["飲み会", "無茶ぶり", "度胸"],
  },
  {
    text: "つい奢りたくなる空気に弱い度合いは？",
    profile: "scale5",
    minLabel: "冷静",
    maxLabel: "かなり弱い",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["飲み会", "お金", "ノリ"],
  },
  {
    text: "好きな人がその場にいたら席替えしたくなる度合いは？",
    profile: "percent",
    minLabel: "気にしない",
    maxLabel: "かなり動く",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["飲み会", "恋愛", "席"],
  },
  {
    text: "カラオケで『みんな知ってる曲』を優先する度合いは？",
    profile: "custom4",
    minLabel: "自分の好き曲優先",
    maxLabel: "場優先",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "カラオケ", "選曲"],
    scaleLabels: ["自分優先", "やや自分", "やや場優先", "場優先"],
  },
  {
    text: "飲み会で隣の人と深い話まで行く速さは？",
    profile: "scale10",
    minLabel: "かなり遅い",
    maxLabel: "かなり早い",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["飲み会", "会話", "深さ"],
  },
];

const lightSeeds: QuestionSeed[] = [
  {
    text: "理想の昼寝時間は何分？",
    profile: "minutes120",
    minLabel: "短め",
    maxLabel: "長め",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "睡眠", "日常"],
  },
  {
    text: "休日に家を出るまで何分くらいかかる？",
    profile: "minutes180",
    minLabel: "すぐ出る",
    maxLabel: "かなりかかる",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "休日", "支度"],
  },
  {
    text: "辛いものへの耐性はどれくらい？",
    profile: "scale10",
    minLabel: "かなり弱い",
    maxLabel: "かなり強い",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "食べ物", "味覚"],
  },
  {
    text: "甘いものは別腹だと思う度合いは？",
    profile: "scale5",
    minLabel: "思わない",
    maxLabel: "かなり思う",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "食べ物", "甘味"],
  },
  {
    text: "映画のネタバレを許せる度合いは？",
    profile: "scale10",
    minLabel: "絶対いや",
    maxLabel: "わりと平気",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "映画", "ネタバレ"],
  },
  {
    text: "旅行前の荷造りは何日前から始める？",
    profile: "stepperCount",
    minLabel: "当日派",
    maxLabel: "かなり前",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "旅行", "準備"],
  },
  {
    text: "コンビニに寄り道しがちな回数は週に何回？",
    profile: "stepperCount",
    minLabel: "あまり寄らない",
    maxLabel: "かなり寄る",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "日常", "コンビニ"],
  },
  {
    text: "服を決めるのにかかる時間は？",
    profile: "minutes120",
    minLabel: "即決",
    maxLabel: "かなり悩む",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "服装", "支度"],
  },
  {
    text: "お風呂は長風呂しがちなほう？",
    profile: "minutes120",
    minLabel: "さっと派",
    maxLabel: "かなり長い",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "生活", "お風呂"],
  },
  {
    text: "目覚ましのスヌーズを押す回数は？",
    profile: "stepperCount",
    minLabel: "押さない",
    maxLabel: "かなり押す",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "朝", "習慣"],
  },
  {
    text: "行列に並べる限界は何分くらい？",
    profile: "minutes180",
    minLabel: "すぐ諦める",
    maxLabel: "かなり待てる",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "待ち時間", "忍耐"],
  },
  {
    text: "キャッシュレス派の度合いは？",
    profile: "percent",
    minLabel: "現金派",
    maxLabel: "ほぼキャッシュレス",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "買い物", "お金"],
  },
  {
    text: "寝る前にスマホを見る時間は？",
    profile: "minutes180",
    minLabel: "ほぼ見ない",
    maxLabel: "かなり見る",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "スマホ", "夜"],
  },
  {
    text: "家の片付けにこだわる度合いは？",
    profile: "scale10",
    minLabel: "ざっくり",
    maxLabel: "かなりこだわる",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "片付け", "生活"],
  },
  {
    text: "早起きの得意さは？",
    profile: "scale5",
    minLabel: "かなり苦手",
    maxLabel: "かなり得意",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "朝", "生活"],
  },
  {
    text: "予定のない休日でも満足できる度合いは？",
    profile: "scale10",
    minLabel: "予定ほしい",
    maxLabel: "かなり満足",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "休日", "価値観"],
  },
  {
    text: "つい同じメニューを頼みがちな度合いは？",
    profile: "scale5",
    minLabel: "毎回変えたい",
    maxLabel: "かなり固定",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "食事", "習慣"],
  },
  {
    text: "雨の日に傘を忘れず持っていける自信は？",
    profile: "percent",
    minLabel: "かなり忘れる",
    maxLabel: "ほぼ忘れない",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "天気", "持ち物"],
  },
  {
    text: "おみやげ選びにかける時間は？",
    profile: "minutes120",
    minLabel: "さっと決める",
    maxLabel: "かなり悩む",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "旅行", "買い物"],
  },
  {
    text: "家ではどのくらい『ながら作業』しがち？",
    profile: "custom6",
    minLabel: "一点集中",
    maxLabel: "常にながら",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["ライト", "生活", "習慣"],
    scaleLabels: ["集中派", "少しながら", "ほどほど", "わりとながら", "かなりながら", "常にながら"],
  },
];

const extraAcquaintanceSeeds: QuestionSeed[] = [
  {
    text: "初対面の場で『この人おもしろい』と思ったら話しかけにいく速さは？",
    profile: "scale10",
    minLabel: "かなり様子見",
    maxLabel: "かなり早い",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "第一印象", "行動"],
  },
  {
    text: "自己紹介で自分の出身地ネタを使う頻度は？",
    profile: "scale5",
    minLabel: "ほぼ使わない",
    maxLabel: "かなり使う",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "自己紹介", "話題"],
  },
  {
    text: "相手の話にリアクションを大きめに返す度合いは？",
    profile: "scale10",
    minLabel: "かなり控えめ",
    maxLabel: "かなり大きい",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "リアクション", "会話"],
  },
  {
    text: "初対面の人と笑いのツボが違っても気まずくならない度合いは？",
    profile: "scale5",
    minLabel: "気まずい",
    maxLabel: "かなり平気",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "笑い", "空気感"],
  },
  {
    text: "初対面の相手の服装や雰囲気を褒めるまでの速さは？",
    profile: "scale10",
    minLabel: "かなり慎重",
    maxLabel: "かなり早い",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "褒め", "距離感"],
  },
  {
    text: "初対面の場で自分から席替えや移動を提案できる度合いは？",
    profile: "percent",
    minLabel: "ほぼしない",
    maxLabel: "かなりする",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "提案", "場づくり"],
  },
  {
    text: "相手の緊張をほぐすために冗談を入れられる度合いは？",
    profile: "scale5",
    minLabel: "入れない",
    maxLabel: "かなり入れられる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "緊張", "ユーモア"],
  },
  {
    text: "初対面で『この人とは合いそう』と判断するまで何分くらい？",
    profile: "minutes120",
    minLabel: "かなり早い",
    maxLabel: "じっくり見る",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "直感", "相性"],
  },
  {
    text: "相手の話を広げるために追加質問を重ねる頻度は？",
    profile: "scale10",
    minLabel: "少なめ",
    maxLabel: "かなり多い",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "質問", "会話"],
  },
  {
    text: "初対面の人にニックネームで呼んでいいか聞くまでの慎重さは？",
    profile: "scale10",
    minLabel: "すぐ聞ける",
    maxLabel: "かなり慎重",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "呼び方", "距離感"],
  },
  {
    text: "初対面の場で『また集まりましょう』を自分から言う確率は？",
    profile: "percent",
    minLabel: "ほぼ言わない",
    maxLabel: "かなり言う",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "次回", "社交性"],
  },
  {
    text: "初対面の相手に自分の失敗エピソードを出せる深さは？",
    profile: "custom4",
    minLabel: "かなり浅い",
    maxLabel: "わりと深い",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "自己開示", "会話"],
    scaleLabels: ["無難だけ", "少し出す", "わりと出す", "かなり出す"],
  },
  {
    text: "初対面の飲み会で自分の席の周辺以外とも話しにいく度合いは？",
    profile: "scale5",
    minLabel: "そのまま",
    maxLabel: "かなり動く",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "飲み会", "行動力"],
  },
  {
    text: "初対面の場で話題が切れたとき、すぐ次を出せる自信は？",
    profile: "scale10",
    minLabel: "かなり不安",
    maxLabel: "かなりある",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "会話", "切り返し"],
  },
  {
    text: "相手のテンションに合わせて声量まで変える柔軟さは？",
    profile: "scale5",
    minLabel: "あまり変えない",
    maxLabel: "かなり合わせる",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["初対面", "空気", "柔軟性"],
  },
  {
    text: "初対面の人の話を覚えて次に会ったとき拾える自信は？",
    profile: "percent",
    minLabel: "かなり不安",
    maxLabel: "かなりある",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "記憶", "印象"],
  },
  {
    text: "初対面の場で『自分らしさ』を出すまでの時間は？",
    profile: "minutes120",
    minLabel: "かなり早い",
    maxLabel: "かなり遅い",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "素", "時間"],
  },
  {
    text: "初対面で年齢や仕事の話題に入るハードルは？",
    profile: "scale10",
    minLabel: "かなり低い",
    maxLabel: "かなり高い",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "話題選び", "距離感"],
  },
  {
    text: "初対面の場で、相手の話に『それわかる』を言いすぎないよう意識する度合いは？",
    profile: "scale5",
    minLabel: "あまり意識しない",
    maxLabel: "かなり意識する",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "共感", "会話"],
  },
  {
    text: "初対面の人と会話が弾んだあと、あとで1人で反省会しがちな度合いは？",
    profile: "scale10",
    minLabel: "ほぼしない",
    maxLabel: "かなりする",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["初対面", "振り返り", "性格"],
  },
];

const extraFriendsSeeds: QuestionSeed[] = [
  {
    text: "友達に急に『今ひま？』と呼ばれて動ける速さは？",
    profile: "scale10",
    minLabel: "かなり遅い",
    maxLabel: "かなり早い",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "呼び出し", "フッ軽"],
  },
  {
    text: "友達のちょっとした嘘なら見逃せる度合いは？",
    profile: "scale5",
    minLabel: "気になる",
    maxLabel: "かなり流せる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "許容", "信頼"],
  },
  {
    text: "一緒に旅行する友達なら、何泊までなら平気？",
    profile: "stepperCount",
    minLabel: "短めがいい",
    maxLabel: "かなり長くて平気",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "旅行", "距離感"],
  },
  {
    text: "友達の新しい恋人の話を、どれくらい本気で聞くタイプ？",
    profile: "scale10",
    minLabel: "軽く聞く",
    maxLabel: "かなり本気で聞く",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "恋バナ", "会話"],
  },
  {
    text: "友達との写真をあとから見返す頻度は？",
    profile: "scale5",
    minLabel: "ほぼ見ない",
    maxLabel: "かなり見る",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "写真", "思い出"],
  },
  {
    text: "友達におすすめされた作品を実際に触る確率は？",
    profile: "percent",
    minLabel: "かなり低い",
    maxLabel: "かなり高い",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "おすすめ", "趣味"],
  },
  {
    text: "友達の長文メッセージに長文で返す率は？",
    profile: "percent",
    minLabel: "短く返す",
    maxLabel: "かなり長く返す",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "LINE", "温度感"],
  },
  {
    text: "友達の黒歴史をいじるときの手加減度合いは？",
    profile: "scale10",
    minLabel: "かなり容赦ない",
    maxLabel: "かなり手加減する",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "いじり", "距離感"],
  },
  {
    text: "友達の相談に対して、共感より解決策を出しがちな度合いは？",
    profile: "scale5",
    minLabel: "共感派",
    maxLabel: "解決策派",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "相談", "スタイル"],
  },
  {
    text: "友達の家に行くなら、片付いてなくても平気な度合いは？",
    profile: "scale10",
    minLabel: "かなり気になる",
    maxLabel: "かなり平気",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "家", "生活感"],
  },
  {
    text: "友達に『それ違うと思う』をちゃんと言える強さは？",
    profile: "scale10",
    minLabel: "かなり言えない",
    maxLabel: "かなり言える",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "意見", "率直さ"],
  },
  {
    text: "久しぶりに会う友達とも、前回の続きみたいに話せる度合いは？",
    profile: "scale5",
    minLabel: "少し距離が出る",
    maxLabel: "すぐ戻る",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "再会", "距離感"],
  },
  {
    text: "友達との予定は、カレンダーに先に入れておきたいタイプ？",
    profile: "custom4",
    minLabel: "その場で決めたい",
    maxLabel: "かなり先に押さえたい",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "予定", "計画性"],
    scaleLabels: ["当日派", "近場で決める", "少し前に決める", "かなり前に決める"],
  },
  {
    text: "友達に貸したものを返してほしいと言い出すまで何日待てる？",
    profile: "stepperCount",
    minLabel: "すぐ言う",
    maxLabel: "かなり待つ",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "貸し借り", "遠慮"],
  },
  {
    text: "友達のSNS投稿にリアクションする頻度は？",
    profile: "scale5",
    minLabel: "ほぼしない",
    maxLabel: "かなりする",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "SNS", "反応"],
  },
  {
    text: "友達とおそろいの物を持つことへの抵抗感は？",
    profile: "scale10",
    minLabel: "かなり低い",
    maxLabel: "かなり高い",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "おそろい", "価値観"],
  },
  {
    text: "友達が落ち込んでいるとき、そっとしておく判断ができる度合いは？",
    profile: "scale5",
    minLabel: "すぐ話しかける",
    maxLabel: "ちゃんと待てる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "気遣い", "距離感"],
  },
  {
    text: "友達と遊んだあと『楽しかった』を自分から送る確率は？",
    profile: "percent",
    minLabel: "ほぼ送らない",
    maxLabel: "かなり送る",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "フォロー", "連絡"],
  },
  {
    text: "友達のセンスを信用して買い物を任せられる度合いは？",
    profile: "scale10",
    minLabel: "かなり任せにくい",
    maxLabel: "かなり任せられる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["友達", "買い物", "信頼"],
  },
  {
    text: "友達グループの中で、自分は『聞く側』だと思う度合いは？",
    profile: "scale5",
    minLabel: "話す側",
    maxLabel: "聞く側",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["友達", "役割", "会話"],
  },
];

const extraRomanceSeeds: QuestionSeed[] = [
  {
    text: "好きな人とのLINEで、返信文面を考え直す回数は？",
    profile: "stepperCount",
    minLabel: "ほぼ直さない",
    maxLabel: "かなり直す",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "LINE", "慎重さ"],
  },
  {
    text: "相手からの好意に気づくのは早いほう？",
    profile: "scale10",
    minLabel: "かなり鈍い",
    maxLabel: "かなり早い",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "好意", "察知"],
  },
  {
    text: "好きな人の前で空回りしたあと、引きずる時間は？",
    profile: "minutes180",
    minLabel: "すぐ切り替える",
    maxLabel: "かなり引きずる",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "緊張", "反省"],
  },
  {
    text: "相手の返信速度を気にしてしまう度合いは？",
    profile: "scale5",
    minLabel: "ほぼ気にしない",
    maxLabel: "かなり気にする",
    difficulty: 1,
    spicyLevel: 2,
    tags: ["恋愛", "返信", "不安"],
  },
  {
    text: "恋人と過ごすなら、会話より一緒にぼーっとする時間も大事だと思う度合いは？",
    profile: "scale10",
    minLabel: "会話重視",
    maxLabel: "静かな時間も大事",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["恋愛", "過ごし方", "価値観"],
  },
  {
    text: "好きな人に嫉妬したとき、態度に出るまでの速さは？",
    profile: "scale10",
    minLabel: "かなり出にくい",
    maxLabel: "かなり早い",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "嫉妬", "態度"],
  },
  {
    text: "恋愛で『追いたい』気持ちと『追われたい』気持ちの比率は？",
    profile: "custom6",
    minLabel: "かなり追いたい",
    maxLabel: "かなり追われたい",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "主導権", "距離感"],
    scaleLabels: ["追いたい", "やや追いたい", "少し追いたい", "少し追われたい", "やや追われたい", "追われたい"],
  },
  {
    text: "好きな人の前で自分の弱い部分を見せられる度合いは？",
    profile: "scale5",
    minLabel: "見せにくい",
    maxLabel: "かなり見せられる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "自己開示", "信頼"],
  },
  {
    text: "理想の告白シチュエーションへのこだわりは？",
    profile: "scale10",
    minLabel: "こだわらない",
    maxLabel: "かなりこだわる",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["恋愛", "告白", "理想"],
  },
  {
    text: "恋人が忙しい時期でも、自分の寂しさをうまく扱える度合いは？",
    profile: "percent",
    minLabel: "かなり難しい",
    maxLabel: "かなりできる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "寂しさ", "自立"],
  },
  {
    text: "好きな人のちょっとした一言を深読みしてしまう度合いは？",
    profile: "scale5",
    minLabel: "ほぼしない",
    maxLabel: "かなりする",
    difficulty: 1,
    spicyLevel: 2,
    tags: ["恋愛", "深読み", "不安"],
  },
  {
    text: "相手の価値観が自分と違っても、まず話を聞こうとできる度合いは？",
    profile: "scale10",
    minLabel: "かなり難しい",
    maxLabel: "かなりできる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "価値観", "歩み寄り"],
  },
  {
    text: "デートのあと、お礼メッセージを送るまでの速さは？",
    profile: "minutes120",
    minLabel: "かなり早い",
    maxLabel: "かなり遅い",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["恋愛", "デート", "連絡"],
  },
  {
    text: "恋愛で『友達期間』を長めにとりたい度合いは？",
    profile: "scale10",
    minLabel: "かなり短めでいい",
    maxLabel: "かなり長めがいい",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["恋愛", "進展", "慎重さ"],
  },
  {
    text: "相手の好きなものを自分でも好きになろうとする度合いは？",
    profile: "scale5",
    minLabel: "あまりしない",
    maxLabel: "かなりする",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["恋愛", "歩み寄り", "趣味"],
  },
  {
    text: "好きな人が他の人に優しいとき、モヤっとしやすい度合いは？",
    profile: "scale10",
    minLabel: "ほぼしない",
    maxLabel: "かなりする",
    difficulty: 1,
    spicyLevel: 2,
    tags: ["恋愛", "嫉妬", "感情"],
  },
  {
    text: "恋愛で『言わなくてもわかってほしい』を期待しがちな度合いは？",
    profile: "scale5",
    minLabel: "かなり言葉にする",
    maxLabel: "かなり期待する",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "期待", "コミュニケーション"],
  },
  {
    text: "恋人とケンカしたあと、自分から歩み寄るまで何時間くらい？",
    profile: "minutes180",
    minLabel: "かなり早い",
    maxLabel: "かなり時間がかかる",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["恋愛", "ケンカ", "仲直り"],
  },
  {
    text: "『好き』を言葉で伝える頻度は？",
    profile: "custom4",
    minLabel: "かなり少ない",
    maxLabel: "かなり多い",
    difficulty: 1,
    spicyLevel: 2,
    tags: ["恋愛", "言葉", "愛情表現"],
    scaleLabels: ["ほぼ言わない", "たまに言う", "わりと言う", "かなり言う"],
  },
  {
    text: "恋愛において、相手に合わせすぎないようブレーキをかけられる度合いは？",
    profile: "percent",
    minLabel: "かなり難しい",
    maxLabel: "かなりできる",
    sortOrder: "desc",
    difficulty: 3,
    spicyLevel: 2,
    tags: ["恋愛", "自分軸", "バランス"],
  },
];

const extraPartySeeds: QuestionSeed[] = [
  {
    text: "飲み会の最初の席で、隣の人と仲良くなる速さは？",
    profile: "scale10",
    minLabel: "かなり遅い",
    maxLabel: "かなり早い",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "会話", "初動"],
  },
  {
    text: "飲み会の途中で水をちゃんと挟む意識は？",
    profile: "scale5",
    minLabel: "ほぼない",
    maxLabel: "かなりある",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "お酒", "自己管理"],
  },
  {
    text: "その場のノリでデザートや追加注文を頼みがちな度合いは？",
    profile: "scale10",
    minLabel: "かなり慎重",
    maxLabel: "かなり頼む",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "注文", "ノリ"],
  },
  {
    text: "飲み会でトイレから戻ってきた人に会話の流れを説明する親切さは？",
    profile: "scale5",
    minLabel: "あまりしない",
    maxLabel: "かなりする",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["飲み会", "気配り", "会話"],
  },
  {
    text: "飲み会で話題がしんだ瞬間、立て直しに入れる度合いは？",
    profile: "scale10",
    minLabel: "かなり難しい",
    maxLabel: "かなり得意",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["飲み会", "会話", "立て直し"],
  },
  {
    text: "割り勘計算を自分からやる率は？",
    profile: "percent",
    minLabel: "ほぼやらない",
    maxLabel: "かなりやる",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "会計", "役割"],
  },
  {
    text: "飲み会の空気がゆるんできた時にゲームを挟みたくなる度合いは？",
    profile: "scale5",
    minLabel: "そのままでいい",
    maxLabel: "かなり挟みたい",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "ゲーム", "盛り上げ"],
  },
  {
    text: "気になる人がいる飲み会で、目線を送りすぎない自信は？",
    profile: "percent",
    minLabel: "かなりない",
    maxLabel: "かなりある",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 2,
    tags: ["飲み会", "恋愛", "視線"],
  },
  {
    text: "飲み会の途中で席を移動してでも話したい相手ができる頻度は？",
    profile: "scale10",
    minLabel: "ほぼない",
    maxLabel: "かなりある",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["飲み会", "席移動", "交流"],
  },
  {
    text: "終盤の飲み会でテンションを落とさず保てる度合いは？",
    profile: "scale5",
    minLabel: "かなり落ちる",
    maxLabel: "かなり保てる",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "体力", "テンション"],
  },
  {
    text: "飲み会で初めて食べるメニューに手を出す積極性は？",
    profile: "scale10",
    minLabel: "かなり保守的",
    maxLabel: "かなり積極的",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "食べ物", "冒険"],
  },
  {
    text: "飲み会のあとにそのまま散歩や寄り道をしたくなる度合いは？",
    profile: "scale5",
    minLabel: "すぐ帰りたい",
    maxLabel: "かなりしたい",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "帰り道", "余韻"],
  },
  {
    text: "その場の空気が寒くなった時、笑って回収できる度合いは？",
    profile: "scale10",
    minLabel: "かなり難しい",
    maxLabel: "かなり得意",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["飲み会", "空気", "フォロー"],
  },
  {
    text: "飲み会で1人だけ静かな人にも話を振れる度合いは？",
    profile: "scale5",
    minLabel: "かなり難しい",
    maxLabel: "かなりできる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["飲み会", "気配り", "会話"],
  },
  {
    text: "飲み会で自分の失敗談をネタにできる度合いは？",
    profile: "scale10",
    minLabel: "かなりできない",
    maxLabel: "かなりできる",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["飲み会", "自虐", "ユーモア"],
  },
  {
    text: "乾杯前の微妙な待ち時間を気まずくしない力は？",
    profile: "scale5",
    minLabel: "かなり弱い",
    maxLabel: "かなり強い",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["飲み会", "空気", "初動"],
  },
  {
    text: "盛り上がっている時ほど、周りの酔い具合を見られる冷静さは？",
    profile: "percent",
    minLabel: "かなり低い",
    maxLabel: "かなり高い",
    sortOrder: "desc",
    difficulty: 2,
    spicyLevel: 1,
    tags: ["飲み会", "観察", "冷静さ"],
  },
  {
    text: "飲み会で店員さんを呼ぶ役に自然となりがちな度合いは？",
    profile: "scale10",
    minLabel: "かなりならない",
    maxLabel: "かなりなる",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "役割", "注文"],
  },
  {
    text: "飲み会の写真で変顔やポーズに乗れる度合いは？",
    profile: "custom4",
    minLabel: "かなり乗れない",
    maxLabel: "かなり乗れる",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "写真", "ノリ"],
    scaleLabels: ["乗れない", "少し乗れる", "わりと乗れる", "かなり乗れる"],
  },
  {
    text: "飲み会で『もう1軒だけ』に心が揺れる度合いは？",
    profile: "scale10",
    minLabel: "かなり揺れない",
    maxLabel: "かなり揺れる",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["飲み会", "二次会", "誘惑"],
  },
];

const extraLightSeeds: QuestionSeed[] = [
  {
    text: "カフェで席に着いてから注文を決めるまでの速さは？",
    profile: "minutes120",
    minLabel: "かなり早い",
    maxLabel: "かなり悩む",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "カフェ", "決断"],
  },
  {
    text: "寝る前に『明日から頑張ろう』と思いがちな度合いは？",
    profile: "scale5",
    minLabel: "あまり思わない",
    maxLabel: "かなり思う",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "夜", "気分"],
  },
  {
    text: "新しい文房具や便利グッズに弱い度合いは？",
    profile: "scale10",
    minLabel: "かなり強い",
    maxLabel: "かなり弱い",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "買い物", "雑貨"],
  },
  {
    text: "冷蔵庫の中身を把握できている自信は？",
    profile: "percent",
    minLabel: "かなりない",
    maxLabel: "かなりある",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "生活", "家事"],
  },
  {
    text: "スマホの写真フォルダを整理する頻度は？",
    profile: "scale5",
    minLabel: "ほぼしない",
    maxLabel: "かなりする",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "スマホ", "整理"],
  },
  {
    text: "アイスを食べるなら、カップよりコーン派な度合いは？",
    profile: "scale10",
    minLabel: "かなりカップ派",
    maxLabel: "かなりコーン派",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "食べ物", "好み"],
  },
  {
    text: "家で動画を見るとき、倍速にしがちな度合いは？",
    profile: "scale5",
    minLabel: "ほぼしない",
    maxLabel: "かなりする",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "動画", "習慣"],
  },
  {
    text: "外出前に天気予報をちゃんと確認する率は？",
    profile: "percent",
    minLabel: "かなり低い",
    maxLabel: "かなり高い",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "天気", "習慣"],
  },
  {
    text: "朝ごはんをちゃんと食べたい度合いは？",
    profile: "scale10",
    minLabel: "食べなくて平気",
    maxLabel: "かなり食べたい",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "朝", "食事"],
  },
  {
    text: "部屋の照明は明るめが好き？",
    profile: "scale5",
    minLabel: "かなり暗め派",
    maxLabel: "かなり明るめ派",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "部屋", "好み"],
  },
  {
    text: "気になる店を見つけたら、その場で保存するマメさは？",
    profile: "percent",
    minLabel: "かなり低い",
    maxLabel: "かなり高い",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "メモ", "習慣"],
  },
  {
    text: "洗濯物はたたむより、まず置きがちな度合いは？",
    profile: "scale10",
    minLabel: "すぐたたむ",
    maxLabel: "かなり置く",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "家事", "生活"],
  },
  {
    text: "ネットで買い物する時、口コミを読み込む時間は？",
    profile: "minutes180",
    minLabel: "すぐ決める",
    maxLabel: "かなり読む",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "買い物", "比較"],
  },
  {
    text: "新しい店に入るより、行きつけを選びがちな度合いは？",
    profile: "scale5",
    minLabel: "新規派",
    maxLabel: "行きつけ派",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "外食", "安定志向"],
  },
  {
    text: "傘をなくしやすい度合いは？",
    profile: "scale10",
    minLabel: "かなりなくしにくい",
    maxLabel: "かなりなくしやすい",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "持ち物", "あるある"],
  },
  {
    text: "テレビや動画を見ながらスマホも触ってしまう度合いは？",
    profile: "scale5",
    minLabel: "ほぼしない",
    maxLabel: "かなりする",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "ながら", "スマホ"],
  },
  {
    text: "今日は早く寝ようと思ってから、実際に寝るまで何分かかる？",
    profile: "minutes180",
    minLabel: "かなり早い",
    maxLabel: "かなりかかる",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "夜", "生活"],
  },
  {
    text: "旅行先で朝から動きたいタイプ？",
    profile: "scale10",
    minLabel: "かなりゆっくり",
    maxLabel: "かなり朝から",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "旅行", "朝"],
  },
  {
    text: "財布の中のレシートをため込みがちな度合いは？",
    profile: "scale5",
    minLabel: "すぐ捨てる",
    maxLabel: "かなりためる",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "財布", "生活"],
  },
  {
    text: "スーパーで予定外のおやつを買ってしまう率は？",
    profile: "percent",
    minLabel: "かなり低い",
    maxLabel: "かなり高い",
    sortOrder: "desc",
    difficulty: 1,
    spicyLevel: 1,
    tags: ["ライト", "買い物", "おやつ"],
  },
];

export const questionBank: Question[] = [
  ...buildQuestions("acquaintance", acquaintanceSeeds),
  ...buildQuestions(
    "acquaintance",
    extraAcquaintanceSeeds,
    acquaintanceSeeds.length,
  ),
  ...buildQuestions("friends", friendsSeeds),
  ...buildQuestions("friends", extraFriendsSeeds, friendsSeeds.length),
  ...buildQuestions("romance", romanceSeeds),
  ...buildQuestions("romance", extraRomanceSeeds, romanceSeeds.length),
  ...buildQuestions("party", partySeeds),
  ...buildQuestions("party", extraPartySeeds, partySeeds.length),
  ...buildQuestions("light", lightSeeds),
  ...buildQuestions("light", extraLightSeeds, lightSeeds.length),
];

export function getQuestionsByCategory(category: QuestionCategory): Question[] {
  return questionBank.filter((question) => question.category === category);
}
